org: andyweiss1982
app: react-gql-cognito
service: react-gql-cognito
# app and org for use with dashboard.serverless.com
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: personal
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-s3-sync
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

package:
  excludeDevDependencies: false
  individually: true
  exclude:
    - node_modules/**

custom:
  siteName: andy-react-gql-demo-${self:provider.stage}
  tableName: ${self:custom.siteName}-table
  bucketName: ${self:custom.siteName}-bucket
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist

outputs:
  region: ${self:provider.region}
  userPool: !Ref CognitoUserPool
  userPoolClient: !Ref CognitoUserPoolClient

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.siteName}
        Policies:
          PasswordPolicy:
            MinimumLength: 8
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.siteName}
        GenerateSecret: False
        UserPoolId:
          Ref: CognitoUserPool
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthScopes:
          - email
          - openid
        CallbackURLs:
          - http://localhost:1234
        LogoutURLs:
          - http://localhost:1234
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        SupportedIdentityProviders:
          - COGNITO
    CognitoUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId:
          Ref: CognitoUserPool
        Domain: ${self:custom.siteName}-user-pool
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::", { "Ref": "StaticSite" }, "/*"]]
    DynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  graphql:
    handler: backend/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
